server:
  port: 10003
  servlet:
    context-path: /
spring:
  application:
    name: schedule-app
schedule:
  url: "classpath:scheduleConfig.json"

jobs:
  refresh:
    cron: "0 */1 * * * ?"
  my:
    cron: "0 */2 * * * ?"