server:
  port: 10003
  servlet:
    context-path: /
spring:
  application:
    name: schedule-app
#    log level
logging:
  level:
    com:
      mq:
        handler: info
        jobs: warn

schedule:
  url: "classpath:scheduleConfig.json"

jobs:
  refresh:
    cron: "0 */1 * * * ?"
  my:
    cron: "0 */2 * * * ?"

